### ISSUE TITLE
Windows 11 iot enterprise ltsc 2024 released

### ISSUE THREAD

**Issue by BreathBlush** [IceLoveYer/LTSC-Add-MicrosoftStore#2]
Windows 11 iot enterprise ltsc 2024 released, is there any way to add store for ltsc 2024? 

https://learn.microsoft.com/en-us/windows/iot/iot-enterprise/whats-new/windows-11-iot-enterprise-ltsc-2024

Thanks

**Comment by PingZi-Wing** [comment]
以管理员身份Windows PowerShell中执行：wsreset -i

**Comment by BreathBlush** [comment]
> 以管理员身份Windows PowerShell中执行：wsreset -i

感谢！
